image:
  repository: nginx
  tag: 1.27.5-alpine-slim
  pullPolicy: IfNotPresent

affinity: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80